/*
 Navicat Premium Dump SQL

 Source Server         : localhost_3306_pw_123456789
 Source Server Type    : MySQL
 Source Server Version : 90400 (9.4.0)
 Source Host           : localhost:3306
 Source Schema         : temu_app

 Target Server Type    : MySQL
 Target Server Version : 90400 (9.4.0)
 File Encoding         : 65001

 Date: 28/08/2025 17:31:43
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for file_records
-- ----------------------------
DROP TABLE IF EXISTS `file_records`;
CREATE TABLE `file_records` (
  `id` int NOT NULL AUTO_INCREMENT,
  `original_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始文件名',
  `stored_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '存储文件名',
  `file_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文件路径',
  `file_size` bigint NOT NULL COMMENT '文件大小(字节)',
  `file_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件类型',
  `uploaded_by` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '上传用户',
  `upload_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
  PRIMARY KEY (`id`),
  KEY `idx_uploaded_by` (`uploaded_by`),
  KEY `idx_upload_time` (`upload_time`),
  KEY `idx_file_type` (`file_type`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件记录表';

-- ----------------------------
-- Records of file_records
-- ----------------------------
BEGIN;
INSERT INTO `file_records` (`id`, `original_name`, `stored_name`, `file_path`, `file_size`, `file_type`, `uploaded_by`, `upload_time`) VALUES (1, 'catetree.json', '1ec1e934-e185-48f5-92d0-8c8929dbf87b.json', './uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json', 6995, 'application/json', 'admin', '2025-08-15 10:59:22');
INSERT INTO `file_records` (`id`, `original_name`, `stored_name`, `file_path`, `file_size`, `file_type`, `uploaded_by`, `upload_time`) VALUES (2, 'The Swift Programming Language-Chinese.pdf', 'bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf', './uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf', 3856591, 'application/pdf', 'admin', '2025-08-15 11:01:05');
COMMIT;

-- ----------------------------
-- Table structure for operate_log
-- ----------------------------
DROP TABLE IF EXISTS `operate_log`;
CREATE TABLE `operate_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `operate_user` int unsigned DEFAULT NULL COMMENT '操作人ID',
  `operate_username` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作人姓名',
  `operate_time` datetime DEFAULT NULL COMMENT '操作时间',
  `class_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作的类名',
  `method_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作的方法名',
  `method_params` text COLLATE utf8mb4_unicode_ci COMMENT '方法参数',
  `return_value` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '返回值',
  `cost_time` bigint DEFAULT NULL COMMENT '方法执行耗时, 单位:ms',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';

-- ----------------------------
-- Records of operate_log
-- ----------------------------
BEGIN;
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (1, NULL, NULL, '2025-08-15 10:59:10', 'com.czx.service.impl.FileServiceImpl', 'downloadFileByPath', '[./uploads/aead1a24-81ec-4d54-af68-74abfd18994e.docx]', 'isArray', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (2, NULL, NULL, '2025-08-15 10:59:23', 'com.czx.service.impl.FileServiceImpl', 'uploadFile', '[org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile@5f347dde, admin]', '{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22.761592000\",\"uploaded_by\":\"admin\"}', 71);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (3, NULL, NULL, '2025-08-15 10:59:23', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 18);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (4, NULL, NULL, '2025-08-15 10:59:25', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 6);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (5, NULL, NULL, '2025-08-15 10:59:26', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (6, NULL, NULL, '2025-08-15 10:59:27', 'com.czx.service.impl.FileServiceImpl', 'downloadFileByPath', '[./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json]', 'isArray', 0);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (7, NULL, NULL, '2025-08-15 11:00:55', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 41);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (8, NULL, NULL, '2025-08-15 11:00:58', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 9);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (9, NULL, NULL, '2025-08-15 11:00:58', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (10, NULL, NULL, '2025-08-15 11:01:00', 'com.czx.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 34);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (11, NULL, NULL, '2025-08-15 11:01:00', 'com.czx.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (12, NULL, NULL, '2025-08-15 11:01:00', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 7);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (13, NULL, NULL, '2025-08-15 11:01:00', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 6);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (14, NULL, NULL, '2025-08-15 11:01:06', 'com.czx.service.impl.FileServiceImpl', 'uploadFile', '[org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile@3c3e7ae, admin]', '{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05.820214000\",\"uploaded_by\":\"admin\"}', 11);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (15, NULL, NULL, '2025-08-15 11:01:06', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (16, NULL, NULL, '2025-08-15 11:01:08', 'com.czx.service.impl.FileServiceImpl', 'downloadFileByPath', '[./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf]', 'isArray', 6);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (17, NULL, NULL, '2025-08-15 11:01:18', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 10);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (18, NULL, NULL, '2025-08-15 11:01:18', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (19, NULL, NULL, '2025-08-15 11:01:19', 'com.czx.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (20, NULL, NULL, '2025-08-15 11:01:19', 'com.czx.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (21, NULL, NULL, '2025-08-15 11:01:19', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (22, NULL, NULL, '2025-08-15 11:01:19', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (23, NULL, NULL, '2025-08-15 11:01:21', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (24, NULL, NULL, '2025-08-15 11:01:21', 'com.czx.service.impl.FileServiceImpl', 'getAllFiles', '[]', '[{\"file_path\":\"./uploads/bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"file_size\":3856591,\"file_type\":\"application/pdf\",\"id\":2,\"original_name\":\"The Swift Programming Language-Chinese.pdf\",\"stored_name\":\"bfe4027b-5c19-42db-b56e-abd79bfab0b4.pdf\",\"upload_time\":\"2025-08-15T11:01:05\",\"uploaded_by\":\"admin\"},{\"file_path\":\"./uploads/1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"file_size\":6995,\"file_type\":\"application/json\",\"id\":1,\"original_name\":\"catetree.json\",\"stored_name\":\"1ec1e934-e185-48f5-92d0-8c8929dbf87b.json\",\"upload_time\":\"2025-08-15T10:59:22\",\"uploaded_by\":\"admin\"}]', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (25, NULL, NULL, '2025-08-15 14:23:18', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=2, kuajingmaihuo_cookie=1, agentseller_cookie=2, mallid=3, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'false', 1209);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (26, NULL, NULL, '2025-08-15 14:26:12', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=2, kuajingmaihuo_cookie=12, agentseller_cookie=22, mallid=33, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'false', 821);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (27, NULL, NULL, '2025-08-15 14:38:37', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=2, kuajingmaihuo_cookie=12, agentseller_cookie=22, mallid=33, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'false', 455);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (28, NULL, NULL, '2025-08-15 14:38:45', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=2, kuajingmaihuo_cookie=12, agentseller_cookie=22, mallid=33, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'false', 5);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (29, NULL, NULL, '2025-08-15 14:39:09', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=2, kuajingmaihuo_cookie=12, agentseller_cookie=22, mallid=33, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'false', 11);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (30, NULL, NULL, '2025-08-15 14:42:24', 'com.czx.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=1122, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 34);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (31, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 5);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (32, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (33, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (34, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[1, 1, 20]', '{\"success\":false,\"error\":\"用户配置不存在\"}', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (35, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (36, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (37, 1, NULL, '2025-08-15 14:42:25', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[1, 1, 20]', '{\"success\":false,\"error\":\"用户配置不存在\"}', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (38, 1, NULL, '2025-08-15 14:42:39', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', 'null', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (39, 1, NULL, '2025-08-15 14:42:39', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (40, 1, NULL, '2025-08-15 14:42:42', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=1, kuajingmaihuo_cookie=1, agentseller_cookie=2, mallid=3, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'true', 6);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (41, 1, NULL, '2025-08-15 14:43:20', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=1, kuajingmaihuo_cookie=1, agentseller_cookie=2, mallid=3, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'true', 12);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (42, 1, NULL, '2025-08-15 14:43:52', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=1, kuajingmaihuo_cookie=1, agentseller_cookie=2, mallid=3, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'true', 988);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (43, 1, 'admin', '2025-08-15 14:48:30', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=1, kuajingmaihuo_cookie=1, agentseller_cookie=2, mallid=3, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'true', 6);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (44, NULL, NULL, '2025-08-15 14:48:45', 'com.czx.service.impl.UserServiceImpl', 'login', '[User(id=null, username=xiaozhou, password=1122, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', 'null', 9);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (45, NULL, NULL, '2025-08-15 14:49:12', 'com.czx.service.impl.UserServiceImpl', 'login', '[User(id=null, username=xiaozhou, password=1122, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', 'null', 8);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (46, NULL, NULL, '2025-08-15 14:49:15', 'com.czx.service.impl.UserServiceImpl', 'login', '[User(id=null, username=xiaozhou, password=1221, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":2,\"is_active\":1,\"is_admin\":1,\"password\":\"1221\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"xiaozhou\"}', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (47, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.UserServiceImpl', 'findById', '[2]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":2,\"is_active\":1,\"is_admin\":1,\"password\":\"1221\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"xiaozhou\"}', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (48, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', 'null', 10);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (49, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', 'null', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (50, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[2, 1, 20]', '{\"success\":false,\"error\":\"用户配置不存在\"}', 31);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (51, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (52, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', 'null', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (53, 2, 'xiaozhou', '2025-08-15 14:49:15', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[2, 1, 20]', '{\"success\":false,\"error\":\"用户配置不存在\"}', 9);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (54, 2, 'xiaozhou', '2025-08-15 14:49:18', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (55, 2, 'xiaozhou', '2025-08-15 14:49:18', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', 'null', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (56, 2, 'xiaozhou', '2025-08-15 14:49:20', 'com.czx.service.impl.UserConfigServiceImpl', 'saveOrUpdateConfig', '[UserConfig(id=null, user_id=2, kuajingmaihuo_cookie=4, agentseller_cookie=5, mallid=6, parent_msg_id=null, parent_msg_timestamp=null, tool_id=null, created_at=null, updated_at=null)]', 'true', 8);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (57, 2, 'xiaozhou', '2025-08-15 14:55:08', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', '{\"agentseller_cookie\":\"5\",\"created_at\":\"2025-08-15T14:49:20\",\"id\":7,\"kuajingmaihuo_cookie\":\"4\",\"mallid\":\"6\",\"updated_at\":\"2025-08-15T14:49:20\",\"user_id\":2}', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (58, 2, 'xiaozhou', '2025-08-15 14:55:08', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', '{\"agentseller_cookie\":\"5\",\"created_at\":\"2025-08-15T14:49:20\",\"id\":7,\"kuajingmaihuo_cookie\":\"4\",\"mallid\":\"6\",\"updated_at\":\"2025-08-15T14:49:20\",\"user_id\":2}', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (59, 2, 'xiaozhou', '2025-08-15 14:55:08', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[2, 1, 20]', '{\"success\":false,\"error\":\"获取数据失败\"}', 852);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (60, 2, 'xiaozhou', '2025-08-15 14:55:09', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', '{\"agentseller_cookie\":\"5\",\"created_at\":\"2025-08-15T14:49:20\",\"id\":7,\"kuajingmaihuo_cookie\":\"4\",\"mallid\":\"6\",\"updated_at\":\"2025-08-15T14:49:20\",\"user_id\":2}', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (61, 2, 'xiaozhou', '2025-08-15 14:55:09', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', '{\"agentseller_cookie\":\"5\",\"created_at\":\"2025-08-15T14:49:20\",\"id\":7,\"kuajingmaihuo_cookie\":\"4\",\"mallid\":\"6\",\"updated_at\":\"2025-08-15T14:49:20\",\"user_id\":2}', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (62, 2, 'xiaozhou', '2025-08-15 14:55:09', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[2, 1, 20]', '{\"success\":false,\"error\":\"获取数据失败\"}', 717);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (63, 2, 'xiaozhou', '2025-08-15 14:55:12', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', '{\"agentseller_cookie\":\"5\",\"created_at\":\"2025-08-15T14:49:20\",\"id\":7,\"kuajingmaihuo_cookie\":\"4\",\"mallid\":\"6\",\"updated_at\":\"2025-08-15T14:49:20\",\"user_id\":2}', 5);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (64, 2, 'xiaozhou', '2025-08-15 14:55:12', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[2]', '{\"agentseller_cookie\":\"5\",\"created_at\":\"2025-08-15T14:49:20\",\"id\":7,\"kuajingmaihuo_cookie\":\"4\",\"mallid\":\"6\",\"updated_at\":\"2025-08-15T14:49:20\",\"user_id\":2}', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (65, NULL, NULL, '2025-08-15 14:55:35', 'com.czx.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=1122, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (66, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 5);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (67, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', '{\"agentseller_cookie\":\"2\",\"created_at\":\"2025-08-15T14:42:42\",\"id\":6,\"kuajingmaihuo_cookie\":\"1\",\"mallid\":\"3\",\"updated_at\":\"2025-08-15T14:48:29\",\"user_id\":1}', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (68, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', '{\"agentseller_cookie\":\"2\",\"created_at\":\"2025-08-15T14:42:42\",\"id\":6,\"kuajingmaihuo_cookie\":\"1\",\"mallid\":\"3\",\"updated_at\":\"2025-08-15T14:48:29\",\"user_id\":1}', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (69, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[1, 1, 20]', '{\"success\":false,\"error\":\"获取数据失败\"}', 247);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (70, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', '{\"agentseller_cookie\":\"2\",\"created_at\":\"2025-08-15T14:42:42\",\"id\":6,\"kuajingmaihuo_cookie\":\"1\",\"mallid\":\"3\",\"updated_at\":\"2025-08-15T14:48:29\",\"user_id\":1}', 3);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (71, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', '{\"agentseller_cookie\":\"2\",\"created_at\":\"2025-08-15T14:42:42\",\"id\":6,\"kuajingmaihuo_cookie\":\"1\",\"mallid\":\"3\",\"updated_at\":\"2025-08-15T14:48:29\",\"user_id\":1}', 1);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (72, 1, 'admin', '2025-08-15 14:55:35', 'com.czx.service.impl.TemuServiceImpl', 'getComplianceList', '[1, 1, 20]', '{\"success\":false,\"error\":\"获取数据失败\"}', 250);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (73, 1, 'admin', '2025-08-15 14:55:43', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', '{\"agentseller_cookie\":\"2\",\"created_at\":\"2025-08-15T14:42:42\",\"id\":6,\"kuajingmaihuo_cookie\":\"1\",\"mallid\":\"3\",\"updated_at\":\"2025-08-15T14:48:29\",\"user_id\":1}', 6);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (74, 1, 'admin', '2025-08-15 14:55:43', 'com.czx.service.impl.UserConfigServiceImpl', 'getConfigByUserId', '[1]', '{\"agentseller_cookie\":\"2\",\"created_at\":\"2025-08-15T14:42:42\",\"id\":6,\"kuajingmaihuo_cookie\":\"1\",\"mallid\":\"3\",\"updated_at\":\"2025-08-15T14:48:29\",\"user_id\":1}', 2);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (75, NULL, NULL, '2025-08-19 10:28:02', 'com.jsdoctor.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=123456, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', 'null', 118);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (76, NULL, NULL, '2025-08-19 10:28:09', 'com.jsdoctor.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=123456, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', 'null', 4);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (77, NULL, NULL, '2025-08-19 10:28:18', 'com.jsdoctor.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=123456, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', 'null', 5);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (78, NULL, NULL, '2025-08-19 10:28:25', 'com.jsdoctor.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=123456, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', 'null', 16);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (79, NULL, NULL, '2025-08-19 10:29:02', 'com.jsdoctor.service.impl.UserServiceImpl', 'login', '[User(id=null, username=admin, password=1122, email=null, password_hash=null, is_active=null, is_admin=null, created_at=null, updated_at=null)]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 22);
INSERT INTO `operate_log` (`id`, `operate_user`, `operate_username`, `operate_time`, `class_name`, `method_name`, `method_params`, `return_value`, `cost_time`) VALUES (80, 1, 'admin', '2025-08-19 10:29:02', 'com.jsdoctor.service.impl.UserServiceImpl', 'findById', '[1]', '{\"created_at\":\"2025-08-15T10:56:49\",\"email\":\"admin@temu-app.com\",\"id\":1,\"is_active\":1,\"is_admin\":1,\"password\":\"1122\",\"updated_at\":\"2025-08-15T10:56:49\",\"username\":\"admin\"}', 4);
COMMIT;

-- ----------------------------
-- Table structure for user_configs
-- ----------------------------
DROP TABLE IF EXISTS `user_configs`;
CREATE TABLE `user_configs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT '用户ID',
  `kuajingmaihuo_cookie` text COLLATE utf8mb4_unicode_ci COMMENT '跨境猫卖家中心Cookie',
  `agentseller_cookie` text COLLATE utf8mb4_unicode_ci COMMENT 'TEMU代理商中心Cookie',
  `mallid` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MallId',
  `parent_msg_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父消息ID',
  `parent_msg_timestamp` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父消息时间戳',
  `tool_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工具ID',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_config` (`user_id`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `user_configs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户配置表';

-- ----------------------------
-- Records of user_configs
-- ----------------------------
BEGIN;
INSERT INTO `user_configs` (`id`, `user_id`, `kuajingmaihuo_cookie`, `agentseller_cookie`, `mallid`, `parent_msg_id`, `parent_msg_timestamp`, `tool_id`, `created_at`, `updated_at`) VALUES (6, 1, '1', '2', '3', NULL, NULL, NULL, '2025-08-15 14:42:42', '2025-08-15 14:48:29');
INSERT INTO `user_configs` (`id`, `user_id`, `kuajingmaihuo_cookie`, `agentseller_cookie`, `mallid`, `parent_msg_id`, `parent_msg_timestamp`, `tool_id`, `created_at`, `updated_at`) VALUES (7, 2, '4', '5', '6', NULL, NULL, NULL, '2025-08-15 14:49:20', '2025-08-15 14:49:20');
COMMIT;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户名',
  `password` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '密码',
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '邮箱',
  `password_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '密码哈希',
  `is_active` tinyint(1) DEFAULT '1' COMMENT '是否激活',
  `is_admin` tinyint(1) DEFAULT '0' COMMENT '是否管理员',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_username` (`username`),
  KEY `idx_email` (`email`),
  KEY `password` (`password`) USING BTREE,
  KEY `email` (`email`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- ----------------------------
-- Records of users
-- ----------------------------
BEGIN;
INSERT INTO `users` (`id`, `username`, `password`, `email`, `password_hash`, `is_active`, `is_admin`, `created_at`, `updated_at`) VALUES (1, 'admin', '1122', 'admin@temu-app.com', '', 1, 1, '2025-08-15 10:56:49', '2025-08-15 10:56:49');
INSERT INTO `users` (`id`, `username`, `password`, `email`, `password_hash`, `is_active`, `is_admin`, `created_at`, `updated_at`) VALUES (2, 'xiaozhou', '1221', 'admin@temu-app.com', '', 1, 1, '2025-08-15 10:56:49', '2025-08-15 10:56:49');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
